#! /bin/sh

MY_DIR="$(CDPATH='' cd "$(dirname "$0")" && pwd)"
cd "$MY_DIR"

# New build
cat \
  'css/tachyons-4.12.0.min.css' \
  'css/ananke/_code.css' \
  'css/ananke/_hugo-internal-templates.css' \
  'css/ananke/_social-icons.css' \
  'css/ananke/_styles.css' \
  > ../static/dist/css/robinbb.css
