baseURL = "https://robinbb.com/"
languageCode = "en-us"
title = "robinbb"
Copyright = "Copyright 2026 by Robin Bate Boerop. All rights reserved."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 9
enableRobotsTXT = true
disableHugoGeneratorInject = true

[Author]
  name = "Robin Bate Boerop"

# [sitemap]
#   changefreq = "monthly"
#   priority = 0.5
#   filename = "sitemap.xml"

# SectionPagesMenu = "main"
[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  # category = "categories"
  # series = "series"

[params]
  title = "robinbb"
  author = "Robin Bate Boerop"
  description = "Robin Bate Boerop's Blog"
  favicon = "/granola-favicon.ico"
  images = [ "/images/robinbb-profile-color.jpeg", "/images/robinbb-books-background-1.jpeg" ]
  body_classes = "robinbb-dark robinbb-text"
  xdotcom = "https://x.com/robinbateboerop/"
  github = "https://github.com/robinbb/"
  linkedin = "https://www.linkedin.com/in/robinbb/"
  email = "me@robinbb.com"
  instagram = "https://www.instagram.com/robinbateboerop"
  # toc = false
  # featured_image = "/images/robinbb-books-background-1.jpeg"
  # recent_posts_number = 2
  # site_logo = ""
  # facebook = ""
  # youtube = ""
  # mastodon = ""
  # slack = ""
  # stackoverflow = ""
  # rss = ""

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
