#! /bin/sh

set -eu

MY_DIR="$(CDPATH='' cd "$(dirname "$0")" && pwd)"

echo "Testing prerequisites..."
"$MY_DIR"/dev/test-dev-env
echo "... prerequisites tested."
echo
echo "Updating submodules..."
(cd "$MY_DIR" && git submodule update --init)
echo "... submodules updated."
echo
echo "Invoking hugo..."
(cd "$MY_DIR"/hugo && HUGO_ENV='production' hugo)
# ^ Setting HUGO_ENV=production is required to generate the robots.txt file and
#   for enabling Google Analytics.
echo "... done."
