#! /bin/sh

set -e
set -u

MY_DIR="$(CDPATH='' cd "$(dirname "$0")" && pwd)"

echo "Testing prerequisites..."

"$MY_DIR"/dev/test-dev-env
echo "... prerequisites tested."

echo "Building theme..."
( cd "$MY_DIR"/hugo/theme-src  && ./build )
echo "... theme built."

echo "Invoking hugo..."
(cd "$MY_DIR"/hugo && rm -fr public && hugo)
echo "... done."
