#! /usr/bin/env bash

set -euo pipefail

echo "Ensuring 'grep' is present..."
command -v grep > /dev/null
echo "... done."

echo "Ensuring 'hugo' is of the correct version..."
HUGO_VERSION="v0.64.0"
hugo version | grep "Hugo Static Site Generator $HUGO_VERSION"
echo "... version is correct."
